site_name: Guia de Boas-Vindas
site_description: Controladoria-Geral do Estado de Minas Gerais
site_author: Controladoria-Geral do Estado de Minas Gerais

site_url: https://cgemg-ahcs.github.io/guia-de-boas-vindas/

theme:
  name: material
  language: pt
  features:
    - navigation.expand


nav:
  - Início:
      - Apresentação: index.md

  - A CGE-MG:
      - Controladoria-Geral do Estado: cgemg.md
      - Auditoria-Geral: auge.md
      - Corregedoria-Geral: coge.md
      - Subcontroladoria de Transparência, Integridade e Controle Social: suti.md
      - Assessoria de Harmonização das Controladorias Setoriais e Seccionais: ahcs.md
      - Controladorias Setoriais e Seccionais: cset-csec.md

  - Sistemas e Ferramentas:
      - Principais Sistemas Corporativos: sistemas-corporativos.md

  - Serviços e Instrumentos:
      - Denúncias: denuncias.md
      - Consulta Técnica: consulta-tecnica.md
      - Acordo de Leniência: acordo-leniencia.md
      - CAFIMP: cafimp.md
      - Tomada de Contas Especial (TCE): tce.md

  - Planejamento e Controle:
      - PACI: paci.md
      - RACI: raci.md
      - RAG: rag.md

  - Integridade:
      - Política Mineira de Promoção da Integridade (PMPI): pmpi.md
      - Processo Administrativo de Responsabilização (PAR): par.md

  - Gestão de Pessoas:
      - Trilhas de Desenvolvimento: trilhas.md
      - Avaliação de Desempenho: avaliacao-desempenho.md


extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - admonition

docs_dir: docs




  
